name: Docker Image Deployment to Azure Web App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE_NAME: 'kcduong/spaceshop'
  AZURE_WEB_APP: 'spaceshop4u'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Tag the Docker image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}':latest '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Push the Docker image
      run: docker push '${{env.DOCKER_IMAGE_NAME}}':latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPACESHOP_CREDENTIALS }}

    - name: Azure WebApp Deployment
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: '${{env.AZURE_WEB_APP}}'
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: '${{env.DOCKER_IMAGE_NAME}}:latest'
